# Generated by Django 6.0.6 on 2026-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='fingerprints_version',
            field=models.CharField(default='1.0', max_length=100),
        ),
    ]
