# Generated by Django 6.0.6 on 2026-06-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanresult_fingerprints_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='raw_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
